#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = 

INC = 
CFLAGS = -std=c++11 -Wall -Wno-write-strings `wx-config --cxxflags --unicode --version=3.0`
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `wx-config --libs base,core --unicode --version=3.0`

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) 
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/wxMASPersistentManager

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/wxMASPersistentManager

OBJ_DEBUG = $(OBJDIR_DEBUG)/GUI/EvtMainFrame.o $(OBJDIR_DEBUG)/GUI/MainFrame.o $(OBJDIR_DEBUG)/MyApp.o $(OBJDIR_DEBUG)/resource.o $(OBJDIR_DEBUG)/src/MASPersistentManager.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/GUI/EvtMainFrame.o $(OBJDIR_RELEASE)/GUI/MainFrame.o $(OBJDIR_RELEASE)/MyApp.o $(OBJDIR_RELEASE)/resource.o $(OBJDIR_RELEASE)/src/MASPersistentManager.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/GUI || mkdir -p $(OBJDIR_DEBUG)/GUI
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/GUI/EvtMainFrame.o: GUI/EvtMainFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GUI/EvtMainFrame.cpp -o $(OBJDIR_DEBUG)/GUI/EvtMainFrame.o

$(OBJDIR_DEBUG)/GUI/MainFrame.o: GUI/MainFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GUI/MainFrame.cpp -o $(OBJDIR_DEBUG)/GUI/MainFrame.o

$(OBJDIR_DEBUG)/MyApp.o: MyApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MyApp.cpp -o $(OBJDIR_DEBUG)/MyApp.o

$(OBJDIR_DEBUG)/resource.o: resource.rc
	gcc -x c -c -o $(OBJDIR_DEBUG)/resource.o /dev/null

$(OBJDIR_DEBUG)/src/MASPersistentManager.o: src/MASPersistentManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/MASPersistentManager.cpp -o $(OBJDIR_DEBUG)/src/MASPersistentManager.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/GUI
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/GUI || mkdir -p $(OBJDIR_RELEASE)/GUI
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/GUI/EvtMainFrame.o: GUI/EvtMainFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GUI/EvtMainFrame.cpp -o $(OBJDIR_RELEASE)/GUI/EvtMainFrame.o

$(OBJDIR_RELEASE)/GUI/MainFrame.o: GUI/MainFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GUI/MainFrame.cpp -o $(OBJDIR_RELEASE)/GUI/MainFrame.o

$(OBJDIR_RELEASE)/MyApp.o: MyApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MyApp.cpp -o $(OBJDIR_RELEASE)/MyApp.o

$(OBJDIR_RELEASE)/resource.o: resource.rc
	gcc -x c -c -o $(OBJDIR_RELEASE)/resource.o /dev/null

$(OBJDIR_RELEASE)/src/MASPersistentManager.o: src/MASPersistentManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/MASPersistentManager.cpp -o $(OBJDIR_RELEASE)/src/MASPersistentManager.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/GUI
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

virtual_all: debug release

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

