#ifndef __EvtMainFrame__
#define __EvtMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"

//// end generated include

#include <wx/log.h>
#include <wx/arrstr.h>
#include <wx/datetime.h>
#include <wx/textdlg.h>
#include <wx/msgdlg.h>
#include <wx/time.h>
#include <wx/filedlg.h>

#include "MASPersistentManager.h"

#include "snugnika.xpm"

/** Implementing MainFrame */
class EvtMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnBackupMainPersistentButtonClick( wxCommandEvent& event );
		void OnRenameSelectedBackupButtonClick( wxCommandEvent& event );
		void OnRestoreSelectedBackupButtonClick( wxCommandEvent& event );
		void OnDeleteSelectedBackupButtonClick( wxCommandEvent& event );
		void OnOpenSaveFolderButtonClick( wxCommandEvent& event );
		void OnCreateZipButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtMainFrame( wxWindow* parent );
	//// end generated class members
	private:
        MASPersistentManager m_PersistentManager;
        void RefreshPersistentList();
        void InfoMessage(wxString Message);
        void WarningMessage(wxString Message);
        void ErrorMessage(wxString Message);
};

#endif // __EvtMainFrame__
